var game = new Game(alternate)
var player1 = new Player()
var player2 = new Player('Daniel')
game.addPlayers(player1)
game.addPlayers(player2)
player1.takeTurn()
player2.takeTurn(alternate[2])

console.log(game.resolveResults())
console.log(game)